#!/bin/sh

VERSION_FILE="src/snake.version"

if [ -f $VERSION_FILE ]; then
	VERSION_TEXT=$(cat $VERSION_FILE)
	if ! git rev-parse v$VERSION_TEXT >/dev/null 2>&1; then
		git tag -a v$VERSION_TEXT -m "Version $VERSION_TEXT"
		echo Created tag v$VERSION_TEXT
	else
		echo Tag v$VERSION_TEXT already exists
	fi
	if ! git ls-remote --tags origin v$VERSION_TEXT >/dev/null 2>&1; then
		git push origin v$VERSION_TEXT
		echo Pushed tag v$VERSION_TEXT
	else
		echo Remote tag v$VERSION_TEXT already exists
	fi
else
	echo Version file does not exist
	exit -1
fi